### ISSUE TITLE
/token: Authorization header is not set

### ISSUE THREAD

**Issue by bbigras** [badgateway/oauth2-client#70]
I'm using this and the Authorization header doesn't seem to be set in the request:

`clientSecret` is set.

```js
  const oauth2Token = await client.authorizationCode.getToken({
    code: code,
    redirectUri: "http://localhost:3000/callback"
  });
```

I'm wondering if this condition should be `body.grant_type === 'authorization_code'`:

https://github.com/badgateway/oauth2-client/blob/00f1cd3f396201c725b2b2a528f0092dd495671d/src/client.ts#L268-L271

**Comment by evert** [comment]
I was under the assumption that the secret shouldn't be specified, because this request is usually done by browsers and a clientSecret would be kinda pointless there, but it appears from the [specification](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3) that this incorrect; which makes sense now given that the request to the `/token` endpoint could also be done by another server.

So this is a gap in the library, need to fix this!
