### ISSUE TITLE
Support optional audience on clientCredentials call

### ISSUE THREAD

**Issue by South-Paw** [badgateway/oauth2-client#90]
Lib is great 👍, thanks for your hard work!

The [Kinde management API](https://kinde.com/docs/build/get-access-token-for-connecting-securely-to-kindes-api/) requires an `audience` be sent on client credentials grant

On [client.ts#L144](https://github.com/badgateway/oauth2-client/blob/main/src/client.ts#L114)

```ts
// client.ts L144
async clientCredentials(params?: { audience?: string, scope?: string[] }): Promise<OAuth2Token> {
    const body:ClientCredentialsRequest = {
      grant_type: 'client_credentials',
      audience: params?.audience,
      scope: params?.scope?.join(' '),
    };

   // ...
}
```

**Comment by South-Paw** [comment]
Created #91 for this feature 👍

@evert 🙏

**Comment by evert** [comment]
Do you know anything about where this parameter is defined? It's not part of the base OAuth2 spec.

**Comment by South-Paw** [comment]
> Do you know anything about where this parameter is defined

Can't find it in a spec - some googling turned up a few results where it's implemented by other providers in their client credential flows as well

When setting up OAuth2 client credential grants in both Postman and Insomnia they have advanced options that allow for an `audience` to be passed with the OAuth2 client credentials flow

![image](https://user-images.githubusercontent.com/2154764/232347959-bd0d7382-9720-49b8-a263-1e632bec0135.png)

**Comment by evert** [comment]
One of the issues with not having a central authority explaining what it is, I also don't know if I'm implementing something that's potentially insecure, or something that should be verified.

Furthermore, I looked around a bit and the format isn't even consistent between vendors. It looks like some at least support multiple values.

Blindly implementing a security feature without following a definition feels like the wrong move for a security product.

If you're willing to put in the legwork, it would go a long way to ask on the [OAuth2 mailing list](https://oauth.net/about/community/) for a recommendation.

**Comment by South-Paw** [comment]
I really don't want to wade into this sort of stuff - I'm just trying to get something implemented so I can carry on with my work.

[OAuth 2.1 spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#RFC8707) mentions issued bearer tokens SHOULD contain an audience restriction in [7.1.3.6](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#section-7.1.3.6), [7.1.5](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#section-7.1.5) and [7.3.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#section-7.3.2) - but with any notes for how the client can define what that audience is, despite that some providers still have added it in their flows.

Looks like [oauth4webapi](https://github.com/panva/oauth4webapi/blob/main/examples/client_credentials.ts) supports custom parameters on a client credentials flow - I'll either use that or just re-publish this package for myself with a 2 line change made 😭

**Comment by evert** [comment]
> I really don't want to wade into that sort of stuff - mailing lists of people discussing stuff is not my thing nor would people be happy I'm spending time on that - I'm just trying to get something implemented so I can carry on with my work.

Don't forget that the reason any of this exists at all is because people _do_ take the time to do this ;)

> [OAuth 2.1 spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#RFC8707) mentions issued bearer tokens SHOULD contain an audience restriction in [7.1.3.6](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#section-7.1.3.6), [7.1.5](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#section-7.1.5) and [7.3.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#section-7.3.2) - but without any notes for how the client can define what that audience is, despite that some providers still have added it in their flows.

My take from those paragraphs is mainly: don't share access tokens across contexts, but yeah I'm also not sure. Honestly _any_ source that seems like a good suggestion on what to do would suffice for me. Whether that's about the `audience` parameter specifically or a good example to follow for other arbitrary/proprietary parameters.

**Comment by brockallen** [comment]
The resource indicator spec is the one that you might want to look into for audience constraining the access tokens: https://datatracker.ietf.org/doc/html/rfc8707

**Comment by evert** [comment]
Hi @South-Paw ,

Appreciate all the research. 

> the only additional parameters that are missing from the library are the client_id, client_secret and resource ones but that's not necessarily why I opened this issue

Note that `client_id` and `client_secret` are supported, but they are passed when creating the client. As for `resource` I agree with @brockallen , the `resource` parameter is well-defined so it's easier to justify because we have some source to figure out the implications.

> I believe this means that this library would not support Auth0's oauth endpoint because this library always(?) [sends the client id and secret via the Authorization header](https://github.com/badgateway/oauth2-client/blob/main/src/client.ts#L268-L273) - where-as Auth0 expects them in the request body and does not support the Authorization header

This still needs to be merged and released, but is planned:

https://github.com/badgateway/oauth2-client/pull/84

Long story short, I think there's basically 2 paths here:

1. Figure out where `audience` comes from. If it's some draft spec I can see this library support this, but adding vendor-specific parameters is definitely a code-smell, so that's a hard no. 
2. Support arbitrary parameters so that users can use to provide *any* additional data. I think this is somewhat reasonable, but then instead of a new `audience` option, I would want a 'extraParameters' option typed as `Record<string, string>`.

Given that there's 2 vendors that use `audience`, and they used such a generic name that also appears in OpenID Connect claims, I suspect that there is some draft out there, so I'd like to get some advice from the list to see what the recommendation for implementors is. (I understand you're a bit nervous asking there, so ill do this)

> As well as that other oauth libraries like [the one I linked earlier](https://github.com/panva/oauth4webapi/blob/main/examples/client_credentials.ts) support additional client_credentials params (though the developer experience of this lib is preferable to that other one smile)

I think keeping a pretty firm grip on what and how we're implementing the protocol will ensure that it will continue to be the better developer experience. I don't think there's harm in treading carefully and being very deliberate about adding features ;)

**Comment by evert** [comment]
Sent: https://mailarchive.ietf.org/arch/msg/oauth/CgWt6uA35UN2VTbOTqZqWHDqjCA/

**Comment by South-Paw** [comment]
> Support arbitrary parameters so that users can use to provide any additional data

This seems like a good approach and I'm more than happy to amend my PR to do this if/when required 👍

> I think keeping a pretty firm grip on what and how we're implementing the protocol will ensure that it will continue to be the better developer experience.

Totally understand what you mean and I think you're right with that approach. With this in mind (and given what that mailing list replies with) adding support for additional parameters (in my view) aligns with that

Thanks again @evert, appreciate you taking the time to communicate on this

**Comment by evert** [comment]
The answer is in.

* `audience` is non-standard
* The `resource` parameter is the way to go, but at least auth0 implemented `audience` before `resource` was standardized.
* So given that we can call these vendor-specific, lets add a generic way for users to add additional parameters instead.

If you're up for modifying your PR to use a general `extraParameters` property instead, I'd be happy to merge that. Just make sure that any known parameters are rejected with an error (`client_id`, `client_secret`, `scope`, `resource`)

**Comment by South-Paw** [comment]
Something like this @evert?

```ts
async clientCredentials(params?: {
  scope?: string[];
  resource?: string[];
  extraParams?: Record<string, string[]>;
}): Promise<OAuth2Token> {
  const disallowed = ["client_id", "client_secret", "scope", "resource"];

  if (params?.extraParams && Object.keys(params.extraParams).filter((key) => disallowed.includes(key)).length > 0) {
    throw new Error(`The following extraParams are disallowed: '${disallowed.join("', '")}'`);
  }

  const body: ClientCredentialsRequest = {
    grant_type: "client_credentials",
    scope: params?.scope?.join(" "),
    resource: params?.resource?.join(" "),
    ...params?.extraParams,
  };

  if (!this.settings.clientSecret) {
    throw new Error("A clientSecret must be provided to use client_credentials");
  }

  return tokenResponseToOAuth2Token(this.request("tokenEndpoint", body));
}
```

**Comment by South-Paw** [comment]
have updated #91

**Comment by South-Paw** [comment]
Updated #91 again and re-requested review 👍
